# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 182674f06fba94b482f4d0f22f998f35ed28a95c4378c2d1d3765c6d6a986246cd2ad5ac422bed15fd71496ae76b38d7f83e07842de4956efb6d0aafad92e017

test:
  secret_key_base: e22b6c06fa851d7b79f257d16d87493484b73a7e94cbfea4b6196275f2e2cd84ccc1cd25458094f02d89200863068b83326f8df0ad52e5d87458af09844a8f9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
